# Generated by DeepSeek deepseek-chat
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "pipeline" / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from anomaly_detection import run_pipeline
from baseline import compute_expected_baselines, load_datasets, merge_context
from scoring import build_alert_candidates, compute_metric_z_scores


def _candidate_map(context_loaded: bool = True) -> dict[str, dict]:
    """Return a date-indexed map of candidate rows for the dataset."""
    context_df, metrics_df = load_datasets(ROOT / "data")
    if context_loaded:
        merged = merge_context(metrics_df, context_df)
        baseline = compute_expected_baselines(merged)
    else:
        baseline = compute_expected_baselines(metrics_df, require_context=False)
    scored = compute_metric_z_scores(baseline)
    candidates = build_alert_candidates(scored, z_threshold=3.0)
    return {row["date"].strftime("%Y-%m-%d"): row for _, row in candidates.iterrows()}


def test_context_loaded_black_friday_is_expected_business_case() -> None:
    """Black Friday should be treated as expected when business context explains the spike."""
    candidate_map = _candidate_map(context_loaded=True)
    row = candidate_map["2025-11-28"]
    metrics = {item["metric"] for item in row["anomalies"]}

    assert "support_tickets" in metrics
    assert "revenue_usd" not in metrics
    assert "orders_count" not in metrics

    alerts = run_pipeline(ROOT / "data")
    black_friday = [alert for alert in alerts if alert["date"] == "2025-11-28"]
    assert black_friday
    assert any(alert.get("is_expected") is True for alert in black_friday)


def test_real_outage_overrides_context_and_is_not_expected() -> None:
    """A true operational outage on Nov 5 should remain a real incident even with campaign context present."""
    candidate_map = _candidate_map(context_loaded=True)
    nov_05 = candidate_map["2025-11-05"]
    metrics = {item["metric"] for item in nov_05["anomalies"]}

    assert {"revenue_usd", "support_tickets"}.issubset(metrics)

    alerts = run_pipeline(ROOT / "data")
    nov_05_alerts = [alert for alert in alerts if alert["date"] == "2025-11-05"]
    assert nov_05_alerts
    assert all(alert.get("is_expected") is False for alert in nov_05_alerts)


def test_revenue_drop_below_20_percent_of_baseline_is_always_unexpected() -> None:
    """A revenue collapse should override any holiday or campaign explanation."""
    context_df, metrics_df = load_datasets(ROOT / "data")
    merged = merge_context(metrics_df, context_df)
    baseline = compute_expected_baselines(merged)
    scored = compute_metric_z_scores(baseline)

    revenue_row = scored[scored["date"] == pd.Timestamp("2025-11-05")]
    assert not revenue_row.empty
    revenue_record = revenue_row.iloc[0]

    revenue_expected = float(revenue_record["revenue_usd_expected"])
    revenue_actual = float(revenue_record["revenue_usd"])
    assert revenue_actual < 0.2 * revenue_expected

    candidate_map = _candidate_map(context_loaded=True)
    alert_row = candidate_map["2025-11-05"]
    revenue_items = [item for item in alert_row["anomalies"] if item["metric"] == "revenue_usd"]
    assert revenue_items
    assert any(
        item["metric"] == "revenue_usd" and item.get("expected", 0) > 0 and item["actual"] < 0.2 * item["expected"]
        for item in revenue_items
    )
    alerts = run_pipeline(ROOT / "data")
    nov_05_alerts = [alert for alert in alerts if alert["date"] == "2025-11-05"]
    assert nov_05_alerts
    assert all(alert.get("is_expected") is False for alert in nov_05_alerts)


def test_support_spike_above_5x_baseline_is_always_unexpected() -> None:
    """Support tickets above 5x baseline should ignore campaign/holiday context and remain an operational incident."""
    context_df, metrics_df = load_datasets(ROOT / "data")
    merged = merge_context(metrics_df, context_df)
    baseline = compute_expected_baselines(merged)
    scored = compute_metric_z_scores(baseline)

    support_row = scored[scored["date"] == pd.Timestamp("2025-11-05")]
    assert not support_row.empty
    support_record = support_row.iloc[0]

    support_expected = float(support_record["support_tickets_expected"])
    support_actual = float(support_record["support_tickets"])
    assert support_actual > 5.0 * support_expected

    alerts = run_pipeline(ROOT / "data")
    alert = next(item for item in alerts if item["date"] == "2025-11-05")
    assert alert["is_expected"] is False


def test_pipeline_covers_october_to_december_2025() -> None:
    """The pipeline should process the full seasonal window and not stop at a short October subset."""
    context_df, metrics_df = load_datasets(ROOT / "data")
    merged = merge_context(metrics_df, context_df)
    baseline = compute_expected_baselines(merged)
    scored = compute_metric_z_scores(baseline)
    candidates = build_alert_candidates(scored, z_threshold=3.0)

    dates = {row["date"].strftime("%Y-%m-%d") for _, row in candidates.iterrows()}
    assert "2025-10-01" <= min(dates) <= "2025-10-31"
    assert "2025-11-05" in dates
    assert "2025-11-28" in dates or "2025-11-28" not in dates
    assert "2025-12-31" >= max(dates) >= "2025-12-01"


def test_context_absent_path_is_rejected() -> None:
    """Without the business context file, the pipeline should fail fast rather than silently mis-scoring context-sensitive periods."""
    data_dir = ROOT / "data"
    with pytest.raises((FileNotFoundError, ValueError)):
        run_pipeline(data_dir / "missing_context")


def test_alert_schema_contains_required_business_fields() -> None:
    """The output contract must include context, severity, and expected-status metadata for the dashboard."""
    alerts = run_pipeline(ROOT / "data")
    assert alerts
    alert = alerts[0]

    required = {
        "date",
        "anomaly_type",
        "severity",
        "confidence",
        "score",
        "expected_value",
        "actual_value",
        "delta",
        "context",
        "is_expected",
        "root_cause_hypotheses",
        "llm_summary",
        "related_metrics",
    }
    assert required.issubset(alert.keys())
    assert isinstance(alert["context"], dict)
    assert isinstance(alert["related_metrics"], list)
    assert isinstance(alert["is_expected"], bool)
