# Generated by DeepSeek deepseek-chat
"""Regression tests for the correlated outage override (spec section 10).

These tests exercise the real pipeline end-to-end against the shipped dataset
in ``data/``. They intentionally avoid hand-built DataFrames so that the
business behaviour under test is the behaviour that actually ships.

Each test docstring explains:
  * the business scenario it covers, and
  * why Gate 3 (human review of thresholds / context completeness) cannot
    verify it.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "pipeline" / "src"))

from anomaly_detection import run_pipeline  # noqa: E402


@pytest.fixture(scope="module")
def alerts():
    """Run the real pipeline once against the real dataset."""
    return run_pipeline(ROOT / "data")


def _by_date(alerts):
    return {alert["date"]: alert for alert in alerts}


def test_correlated_outage_on_2025_11_05_is_critical_and_not_expected(alerts):
    """Business scenario: 2025-11-05 is a genuine correlated operational outage
    (multiple metrics collapse together). The pipeline must classify it as an
    ``outage``, escalate it to ``critical`` severity, and mark it as NOT
    expected — i.e. a real incident that must page a human.

    Why Gate 3 cannot verify this: Gate 3 reviews whether the *thresholds* and
    *context file* are set to the right business values. It cannot confirm that
    the runtime override logic actually fires on the real correlated signal in
    the shipped dataset — that is a behavioural property of the code, which is
    exactly what this test pins down.
    """
    by_date = _by_date(alerts)
    assert "2025-11-05" in by_date, "expected an alert on 2025-11-05"

    alert = by_date["2025-11-05"]
    assert alert["anomaly_type"] == "outage"
    assert alert["severity"] == "critical"
    assert alert["is_expected"] is False


def test_2025_11_05_is_the_only_outage(alerts):
    """Business scenario: the correlated-outage override must be selective.
    Only the genuine multi-metric collapse on 2025-11-05 should be labelled
    ``outage``; every other alert must be a different anomaly type. A pipeline
    that over-fires the outage override would drown operators in false pages.

    Why Gate 3 cannot verify this: whether the override is *too broad* is a
    runtime property of the scoring/override interaction on the real data, not
    something a human can read off the threshold table or the context CSV.
    """
    outage_dates = [a["date"] for a in alerts if a["anomaly_type"] == "outage"]
    assert outage_dates == ["2025-11-05"], (
        f"expected exactly one outage on 2025-11-05, got {outage_dates}"
    )


def test_2025_11_28_is_expected_medium_and_not_outage(alerts):
    """Business scenario: 2025-11-28 is a context-explained anomaly (holiday /
    campaign period). The pipeline must NOT treat it as an outage, must mark it
    ``is_expected`` True, and must keep its severity at ``medium`` — context
    explains the deviation, so it should not be escalated to critical.

    Why Gate 3 cannot verify this: Gate 3 can confirm the context file lists
    the holiday/campaign, but it cannot confirm that the runtime conflict
    resolution actually *downgrades* severity and sets ``is_expected`` True
    when context and severity disagree. That resolution is code behaviour.
    """
    by_date = _by_date(alerts)
    assert "2025-11-28" in by_date, "expected an alert on 2025-11-28"

    alert = by_date["2025-11-28"]
    assert alert["anomaly_type"] != "outage"
    assert alert["is_expected"] is True
    assert alert["severity"] == "medium"


def test_pipeline_emits_exactly_fifteen_alerts(alerts):
    """Business scenario: the shipped dataset should produce exactly 15 alerts.
    This is a regression guard: a change to thresholds, context handling, or
    the outage override that silently adds or drops alerts is a business
    incident in its own right (either alert fatigue or a missed incident).

    Why Gate 3 cannot verify this: the *count* of alerts is an emergent
    property of the whole pipeline running on the real data. No human review of
    the threshold table or context file can predict it; only execution can.
    """
    assert len(alerts) == 15, f"expected 15 alerts, got {len(alerts)}"


def test_outage_override_beats_context_expectation(alerts):
    """Business scenario: conflict resolution — when a correlated outage
    coincides with context that would normally explain an anomaly, the real
    operational outage must win. The 2025-11-05 alert must therefore be
    ``is_expected`` False even though context columns exist for that date.

    Why Gate 3 cannot verify this: this is precisely the "what wins when both
    apply?" question. Gate 3 reviews inputs (thresholds, context); it cannot
    observe which branch the runtime takes when severity and context conflict.
    """
    by_date = _by_date(alerts)
    alert = by_date["2025-11-05"]
    assert alert["anomaly_type"] == "outage"
    assert alert["is_expected"] is False
    assert alert["severity"] == "critical"


def test_expected_context_alert_is_not_escalated_to_critical(alerts):
    """Business scenario: severity override rules — a context-explained anomaly
    (2025-11-28) must not be escalated to ``critical``. Only genuine outages
    earn critical severity; expected context anomalies stay at ``medium``.

    Why Gate 3 cannot verify this: the mapping from "context explains it" to
    "do not escalate" is a runtime decision. Gate 3 can approve the severity
    ladder on paper but cannot confirm the pipeline applies it correctly when
    context and severity interact on real rows.
    """
    by_date = _by_date(alerts)
    alert = by_date["2025-11-28"]
    assert alert["severity"] != "critical"
    assert alert["severity"] == "medium"
    assert alert["is_expected"] is True
