from __future__ import annotations

import json
import os
import re
from pathlib import Path
from urllib import request

ROOT = Path(__file__).resolve().parents[2]
SKILL_PATH = ROOT / "pipeline" / "skills" / "test_engineer.md"
SCORING_PATH = ROOT / "pipeline" / "src" / "scoring.py"
BASELINE_PATH = ROOT / "pipeline" / "src" / "baseline.py"
OUTPUT_PATH = ROOT / "pipeline" / "tests" / "test_pipeline_deepseek.py"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def normalize_generated_code(raw: str) -> str:
    content = raw.strip()

    if content.startswith("```"):
        content = re.sub(r"^```(?:python)?\s*", "", content, flags=re.IGNORECASE)
        content = re.sub(r"\s*```\s*$", "", content, flags=re.DOTALL)

    if "# Generated by DeepSeek deepseek-chat" not in content:
        content = "# Generated by DeepSeek deepseek-chat\n" + content

    return content.rstrip() + "\n"


def build_user_prompt(scoring_src: str, baseline_src: str) -> str:
    return (
        "Generate a pytest regression test file for the anomaly detection pipeline. "
        "Use the business logic in these files as the source of truth.\n\n"
        "Goal: cover threshold logic, context adjustment, and conflict resolution.\n\n"
        "Requirements:\n"
        "- Test business behavior, not implementation details.\n"
        "- Cover the case where holiday/campaign context explains an anomaly.\n"
        "- Cover the case where a real operational outage must override context.\n"
        "- Cover severity override rules and edge-case conflict resolution.\n"
        "- Write valid pytest code.\n"
        "- Include the required header comment at the top exactly as: '# Generated by DeepSeek deepseek-chat'\n\n"
        "=== pipeline/src/scoring.py ===\n"
        f"{scoring_src}\n\n"
        "=== pipeline/src/baseline.py ===\n"
        f"{baseline_src}\n"
    )


def call_deepseek(system_prompt: str, user_prompt: str) -> str:
    api_key = os.getenv("DEEPSEEK_API_KEY")
    if not api_key:
        raise RuntimeError("DEEPSEEK_API_KEY is required")

    payload = {
        "model": "deepseek-chat",
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.2,
    }

    request_data = json.dumps(payload).encode("utf-8")
    req = request.Request(
        "https://api.deepseek.com/v1/chat/completions",
        data=request_data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
            "Accept": "application/json",
        },
        method="POST",
    )

    with request.urlopen(req, timeout=120) as response:
        response_data = json.load(response)

    try:
        return response_data["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError) as exc:
        raise RuntimeError(f"Unexpected DeepSeek response shape: {response_data}") from exc


def main() -> None:
    skill_text = read_text(SKILL_PATH)
    scoring_text = read_text(SCORING_PATH)
    baseline_text = read_text(BASELINE_PATH)

    user_prompt = build_user_prompt(scoring_text, baseline_text)
    generated_code = call_deepseek(skill_text, user_prompt)
    normalized = normalize_generated_code(generated_code)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(normalized, encoding="utf-8")
    print(f"Wrote DeepSeek-generated tests to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
